site_name: Tech Challenge
site_description: >-
  Projeto desenvolvido para as entregas da Pós-Tech da FIAP para
  Software Architecture.
copyright: Copyright &copy; Software Architecture Team 2024
repo_name: tech-challenge
repo_url: https://github.com/software-architecture-fiap/tech-challenge
edit_uri: tree/main/docs
theme:
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - search.highlight
    - search.share
    - search.suggest
  name: material
  language: pt-BR
  favicon: assets/favicon.ico
  logo: assets/favicon.ico
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/lightbulb
        name: Modo Noturno
    - scheme: slate
      primary: pink
      accent: white
      toggle:
        icon: material/lightbulb-outline
        name: Modo Claro
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - mkdocstrings
  - glightbox
extra:
  alternate:
    - name: Portugês
      link: /home/
      lang: pt-BR
nav:
  - Home: "index.md"
  - Docs:
    - Fase 1:
      - DDD: "fase_1/ddd.md"
      - Event Storming: "fase_1/event_storming.md"
      - Entrega: "fase_1/entrega.md"
      - Passo a Passo: "fase_1/steps.md"
    - Fase 2:
      - Clean Code: "fase_2/clean_code.md"
      - Kubernetes: "fase_2/kubernetes.md"
      - Novas Rotas: "fase_2/novas_rotas.md"
      - Passo a Passo: "fase_2/steps.md"

  - Guia:
    - Ambiente: "environment.md"
