apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: web:1.0.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "1"
            ephemeral-storage: "1Gi"
          limits:
            memory: "128Mi"
            cpu: "2"
            ephemeral-storage: "2Gi"
        ports:
        - containerPort: 2000
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:localhost%401988@db:5432/challenge
      - name: log-sidecar
        image: fluentd:latest
        args: ["-c", "/fluentd/etc/fluent.conf"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.5"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - name: shared-logs
          mountPath: /app/logs
      volumes:
      - name: shared-logs
        emptyDir: {}