apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-db.yaml
  - service-db.yaml
  - pvc-db.yaml
  - deployment-web.yaml
  - service-web.yaml
  - pvc-logs.yaml

namePrefix: base-