apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-db.yaml
  - service-db.yaml
  # - pvc-db.yaml
  - deployment-web.yaml
  - service-web.yaml
  # - pvc-logs.yaml
  - hpa-web.yaml
  #TODO
  # - secrets.yaml Add it on the service web and db deployments

images:
  - name: /app/web
    newTag: latest