apiVersion: v1
kind: Secret
metadata:
  name: db-url-secret
type: Opaque
data:
  # encode the DATABASE_URL value in base64
  # echo -n 'postgresql://postgres:localhost%401988@db:5432/challenge' | base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOmxvY2FsaG9zdEAxOTg4QGRiOjU0MzIvY2hhbGxlbmdl

---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-secret
type: Opaque
data:
  # encode the POSTGRES_USER value in base64
  # encode the POSTGRES_USER value in base64
  # echo -n 'postgres' | base64
  POSTGRES_USER: cG9zdGdyZXM=
  # encode the POSTGRES_PASSWORD value in base64
  # echo -n 'localhost@1988' | base64
  POSTGRES_PASSWORD: bG9jYWxob3N0QDE5ODg=