apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Prod criado para reutizar os recursos da base com alterações para produção 
# incluindo variaveis de ambiente ou config de escalabilidade
bases:
  - ../../base