apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dev criado para reutizar os recursos da base e fazer alterações para testes
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment

resources:
- ../base

images:
- name: web
  newName: web
  newTag: v1.0.3-test
