apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dev criado para reutizar os recursos da base e fazer alterações para testes
bases:
  - ../../base

patchesStrategicMerge:
  - example-patch-db-dev.yaml
