name: Linters
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Validating:
    uses: software-architecture-fiap/tech-challenge/.github/lint-flake8-pr-changed-files.yml@main
