name: Comment on Pull Request
on:
  pull_request:
    types: [opened]

jobs:
  post-comment:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Regras para deploy e convenção de nomenclatura da branch.

            **Deploy para o ambiente de desenvolvimento:**
            - Para realizar o deploy no ambiente de desenvolvimento, comente: `/deploy-dev`

            **Deploy para o ambiente produtivo:**
            Este projeto utiliza o SemVer (Versionamento Semântico) para controlar as versões de imagens e tags do repositório. 
            Para realizar o deploy no ambiente de produção, siga as regras abaixo:

            Nomenclatura de Branch por tipo de versão:
            - Patch Version (Correção de bugs): Use o prefixo `bugfix/`.
            - Minor Version (Novas funcionalidades sem mudanças incompatíveis): Use o prefixo `feature/`.
            - Major Version (Mudanças incompatíveis ou significativas): Use o prefixo `release/`.
            - Documentação ou Ajustes Diversos: Use os padrões `doc/` ou `misc/` para incrementar apenas a versão de build (exemplo: v0.0.0+1).

            Certifique-se de seguir essas convenções para garantir um processo de deploy funcione!
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
