name: Pytest
on: [push]

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Copiando os Arquivos do Repositório
        uses: actions/checkout@v3

      - name: Instalando o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalando o Poetry
        run: pipx install poetry

      - name: Instalando Dependências
        run: poetry install

      - name: Executando os Testes
        run: pytest --v
