name: Pytest
on: [push]

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Copiando os Arquivos do Repositório
        uses: actions/checkout@v3

      - name: Instalando o Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Construindo e ativando os containers
        run: docker-compose up -d --build

      - name: Executando testes integrados
        run: docker-compose run tests

      - name: Removendo containers
        run: docker-compose down
