name: Pytest
on: [push]

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Copiando os Arquivos do Repositório
        uses: actions/checkout@v3

      - name: Instalando o Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Construindo e Subindo os Containers
        run: docker-compose up -d --build

      - name: Executando os Testes
        run: docker-compose run tests

      - name: Derrubando os Containers
        run: docker-compose down
