name: Pytest
on: [push, pull_request]

jobs:
  Testing:
    runs-on: ubuntu-latest

    env:
      ADMIN_CPF: {{ secrets.ADMIN_CPF }}
      ADMIN_EMAIL: {{ secrets. }}
      ADMIN_NAME: {{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: {{ secrets.ADMIN_PASSWORD }}
      DATABASE_URL: {{ secrets.DATABASE_URL }}
      SECRET_KEY: {{ secrets.SECRET_KEY }}

    steps:
      - name: Copiando os Arquivos do Repositório
        uses: actions/checkout@v3

      - name: Instalando o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalando o Poetry
        run: pipx install poetry

      - name: Instalando Dependências
        run: poetry install

      - name: Executando os Testes
        run: poetry run task test
