name: Create PR to update CHANGELOG.md
on:
  push:
    tags:
      - '*'

jobs:
  pr-create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Get the latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)"

      - name: Update changelog
        run: |
          LATEST_TAG=${{ steps.get_tag.outputs.tag }}
          echo "## [${LATEST_TAG}] - $(date +'%d-%m-%Y')" >> CHANGELOG.md
          sed -i "1i ## [${LATEST_TAG}] - $(date +'%d-%m-%Y')\n\n### Added\n" CHANGELOG.md

      - name: Generate PR to commit changes using github-actions-bot
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: create pull request"
          title: "chore: create pull request"
          body: "This is an automated pull request to test the create-pull-request action."
          branch: "bump-version-${{ github.sha }}"
          base: "main"
